name: mulms-az
channels:
  - defaults
dependencies:
  - python=3.9.11
  - pip=23.1.2
  - pip:
      - datasets==2.4.0
      - lxml==4.7.1
      - nltk==3.8.1
      - numpy==1.23.5
      - pandas==1.3.2
      - pre-commit==3.3.3
      - puima @ git+https://github.com/annefried/puima@main
      - pyarrow==6.0.1
      - scikit_learn==1.1.1
      - torch==2.1.0
      - tqdm==4.63.0
      - transformers==4.30.0
